# Generated by Django 4.1.1 on 2023-01-01 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kelompok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(max_length=40)),
                ('keterangan', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ikan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('nama_ilmiah', models.CharField(max_length=50)),
                ('img', models.CharField(max_length=30, null=True)),
                ('detail', models.URLField(max_length=100, null=True)),
                ('kelompok_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='uaspbo.kelompok')),
            ],
        ),
    ]
