# Generated by Django 4.1.1 on 2023-01-05 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uaspbo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
