# Generated by Django 4.1.1 on 2023-01-05 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uaspbo', '0002_search'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Search',
        ),
    ]
